[project]
name = "gdp"
version = "0.1.0"
description = "Fourth year GDP project for online RL control of a delta type wing"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "maturin>=1.14.1",
    "pydantic>=2.13.5",
    "pyqtgraph>=0.14.0",
    "pyside6>=6.11.2",
    "qtpy>=2.4.3",
    "ruststuff",
    "snakeviz>=2.2.2",
    "torch>=2.14.1",
]

[tool.uv.sources]
ruststuff = { path = "ruststuff/target/wheels/ruststuff-0.1.0-cp314-cp314-win_amd64.whl" }
